# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 367339acfac58feb7454d3e3d8382a83d3f011a8a2ca303dbda458c9b9883fdd77e9023631827862c77ad673df96d9614905207687aa48e6fc837e68dd3e9b31

test:
  secret_key_base: 4ddf179e2204cdc1b6e76e753693ddf03cfce685b4ddeb28bb501430b2fc7ffc7ab23438abaf9678dbf5c0fb9db99af5032567c8d54f30221bfba41d27e2c579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
